apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  NAME: dG9kb2xpc3Q=
  USER: dXNlcg==
  PASSWORD: dXNlci1wYXNzd29yZA==
  HOST: bXlzcWwtMC5teXNxbC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbA==
  MYSQL_ROOT_PASSWORD: cm9vdC1wYXNzd29yZA==
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: dXNlci1wYXNzd29yZA==