apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # base64 for 'roor-password'
  MYSQL_USER: dXNlcg==                # base64 for 'user'
  MYSQL_PASSWORD: dXNlcl9wYXNz       # base64 for 'user-password'
  DB_NAME: dG9kb2xpc3Q=              # base64 for 'todolist'
  DB_HOST: bXlzcWwtMC5teXNxbC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbA== # base64 for 'mysql-0.mysql.mysql.svc.cluster.local